LittlerootTown_VieuxDresseurHouse_MapScripts::
	.byte 0

LittlerootTown_VieuxDresseurHouse_EventScript_VieuxDresseur::
	msgbox LittlerootTown_VieuxDresseurHouse_Text_VieuxDresseur, MSGBOX_NPC
	end

LittlerootTown_VieuxDresseurHouse_Text_VieuxDresseur:
	.string "Ah, un jeune dresseur !\p"
	.string "De mon temps, j'ai fait le tour de\n"
	.string "HOENN avec mon équipe. Regarde ce\l"
	.string "mur, chaque trophée raconte un combat.\p"
	.string "Un conseil : connaître les types de tes\n"
	.string "POKéMON, et ceux de l'adversaire,\l"
	.string "c'est la moitié du combat gagnée\l"
	.string "avant même la première attaque.$"
