VermilionCity_Mart_hns_MapScripts::
	.byte 0

VermilionCity_Mart_EventScript_BirdMan::
	msgbox VermilionMart_Text_SuperNerd, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_Woman::
	msgbox VermilionMart_Text_Beauty, MSGBOX_NPC
	end

VermilionMart_Text_SuperNerd:
	.string "La TEAM ROCKET n'est plus\n"
	.string "présente à KANTO.\p"
	.string "Rien que ça, ça me rend\n"
	.string "heureux.$"

VermilionMart_Text_Beauty:
	.string "Je pense aller faire du\n"
	.string "shopping à SAFFRON.$"
