VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Je suis le VIEUX PÊCHEUR, l'aîné\n"
	.string "des FRÈRES PÊCHEURS.\p"
	.string "Tu as déjà rencontré le GOUROU\n"
	.string "DE LA PÊCHE au LAKE OF RAGE?\p"
	.string "Il rêve de voir un jour le plus\n"
	.string "grand MAGIKARP du monde.\p"
	.string "Si ça ne te dérange pas,\n"
	.string "pourrais-tu lui montrer tes\l"
	.string "MAGIKARP pêchés?\p"
	.string "Qui sait, tu pêcheras peut-être\n"
	.string "le MAGIKARP de ses rêves.$"

VermilionCity_House1_Text_Photo:
	.string "C'est une photo de gens en\n"
	.string "train de pêcher…\p"
	.string "Ils ont l'air de bien s'amuser…$"
