LittlerootTown_DameBaiesHouse_MapScripts::
	.byte 0

LittlerootTown_DameBaiesHouse_EventScript_DameBaies::
	msgbox LittlerootTown_DameBaiesHouse_Text_DameBaies, MSGBOX_NPC
	end

LittlerootTown_DameBaiesHouse_Text_DameBaies:
	.string "Bienvenue ! Je cultive des Baies\n"
	.string "dans mon jardin, juste derrière.\p"
	.string "Si tu plantes une Baie et que tu\n"
	.string "l'arroses de temps en temps, elle\l"
	.string "donnera d'autres Baies avec le temps.\p"
	.string "Reviens me voir, j'en donne parfois\n"
	.string "à ceux qui prennent soin de leurs\l"
	.string "POKéMON !$"
