#!/usr/bin/env python3
"""Paint every cinematic panel and generate src/data/hns_cinematic_panels.h (asset table).
Run from the repo root: python3 tools/hns_intro/build.py"""
import os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import paint_panels, paint_fuite  # noqa: E402

names = []
for i, f in enumerate((paint_panels.panel1, paint_panels.panel2, paint_panels.panel3,
                       paint_panels.panel4, paint_panels.panel5), 1):
    n = 'panel%d' % i
    print(n, paint_panels.to_gba(f().im, n))
    names.append(n)
for n, f in paint_fuite.PANELS:
    print(n, paint_panels.to_gba(f().im, n))
    names.append(n)

out = ['// Generated by tools/hns_intro/build.py - do not edit by hand.',
       '// Tiles and tilemaps are LZ77-compressed at build time (Makefile rule %.lz: %).', '']
for n in names:
    c = ''.join(p.capitalize() for p in n.split('_'))
    out.append('static const u32 sCinTiles_%s[] = INCBIN_U32("graphics/hns_intro/%s_tiles.bin.lz");' % (c, n))
    out.append('static const u32 sCinMap_%s[] = INCBIN_U32("graphics/hns_intro/%s_map.bin.lz");' % (c, n))
    out.append('static const u16 sCinPal_%s[] = INCBIN_U16("graphics/hns_intro/%s_pal.bin");' % (c, n))
out.append('')
out.append('enum HnsCinPanel {')
for n in names:
    out.append('    CIN_%s,' % n.upper())
out.append('    CIN_PANEL_COUNT')
out.append('};')
out.append('')
out.append('static const struct HnsCinPanelData sCinPanels[CIN_PANEL_COUNT] = {')
for n in names:
    c = ''.join(p.capitalize() for p in n.split('_'))
    out.append('    [CIN_%s] = {sCinTiles_%s, sCinMap_%s, sCinPal_%s, sizeof(sCinPal_%s)},' % (n.upper(), c, c, c, c))
out.append('};')
open(os.path.join(ROOT, 'src/data/hns_cinematic_panels.h'), 'w').write('\n'.join(out) + '\n')
print('wrote src/data/hns_cinematic_panels.h with', len(names), 'panels')
