LittlerootTown_GardienRouteHouse_MapScripts::
	.byte 0

LittlerootTown_GardienRouteHouse_EventScript_GardienRoute::
	msgbox LittlerootTown_GardienRouteHouse_Text_GardienRoute, MSGBOX_NPC
	end

LittlerootTown_GardienRouteHouse_Text_GardienRoute:
	.string "Je m'occupe de l'entretien de la\n"
	.string "ROUTE 1, juste au nord d'ici.\p"
	.string "Cette carte au mur, c'est celle de\n"
	.string "toute la région. Et cette radio me\l"
	.string "prévient dès qu'un POKéMON sauvage\l"
	.string "cause des soucis sur la route.\p"
	.string "Fais attention aux hautes herbes\n"
	.string "si tu pars par là !$"
