LittlerootTown_MmeChenHouse_MapScripts::
	.byte 0

LittlerootTown_MmeChenHouse_EventScript_MmeChen::
	msgbox LittlerootTown_MmeChenHouse_Text_MmeChen, MSGBOX_NPC
	end

LittlerootTown_MmeChenHouse_Text_MmeChen:
	.string "Oh, bonjour ! Tu es le petit\n"
	.string "(la petite) du PROFESSEUR CHEN,\l"
	.string "n'est-ce pas ?\p"
	.string "Un conseil de voisine : les POKéMON\n"
	.string "ont besoin d'être soignés régulièrement\l"
	.string "au CENTRE POKéMON, surtout après un\l"
	.string "combat difficile.\p"
	.string "Prends bien soin de {STR_VAR_1} !$"
