gText_Birch_Welcome::
	.string "Bonjour ! Désolé de t'avoir fait\n"
	.string "attendre !\p"
	.string "Bienvenue dans le monde des\n"
	.string "POKéMON !\p"
	.string "Je m'appelle CHEN.\p"
	.string "Mais tout le monde m'appelle le\n"
	.string "PROFESSEUR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Voici ce qu'on appelle un\n"
	.string "“POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "appelées POKéMON.\p"
	.string "Nous, les humains, vivons à leurs\n"
	.string "côtés, tantôt comme compagnons de\l"
	.string "jeu, tantôt comme partenaires de\l"
	.string "travail.\p"
	.string "Et parfois, nous nous rassemblons\n"
	.string "pour affronter d'autres dresseurs.\p"
	.string "Mais malgré cette proximité, nous\n"
	.string "sommes loin de tout savoir sur\l"
	.string "les POKéMON.\p"
	.string "En réalité, il existe encore de\n"
	.string "nombreux mystères à leur sujet.\p"
	.string "Pour percer ces mystères, je mène\n"
	.string "des recherches depuis des années.\l"
	.string "C'est mon métier.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Et toi, qui es-tu ?$"

gText_Birch_BoyOrGirl::
	.string "Es-tu un garçon ?\n"
	.string "Ou une fille ?$"

gText_Birch_WhatsYourName::
	.string "Très bien.\n"
	.string "Quel est ton nom ?$"

gText_Birch_SoItsPlayer::
	.string "Alors c'est {PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "Ah, très bien !\p"
	.string "Tu es {PLAYER}{KUN}, celui qui\n"
	.string "emménage à BOURG PALETTE, mon\l"
	.string "village natal.\l"
	.string "Je comprends, maintenant !\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Très bien, es-tu prêt ?\p"
	.string "Ta propre aventure est sur le\n"
	.string "point de commencer.\p"
	.string "Prends ton courage à deux mains,\n"
	.string "et plonge dans le monde des\l"
	.string "POKéMON, où t'attendent rêves,\l"
	.string "aventures et amitiés !\p"
	.string "Bien, je t'attendrai plus tard.\n"
	.string "Viens me voir à mon LABORATOIRE\l"
	.string "POKéMON.\p"
	.string "$"
