VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "Tu connais le MAGNET TRAIN?\p"
	.string "C'est une ligne ferroviaire\n"
	.string "qui va jusqu'à GOLDENROD, à\l"
	.string "JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Je veux aller à SAFFRON pour\n"
	.string "voir le MAGNET TRAIN.$"
