// Generated by tools/hns_intro/build.py - do not edit by hand.
// Tiles and tilemaps are LZ77-compressed at build time (Makefile rule %.lz: %).

static const u32 sCinTiles_Panel1[] = INCBIN_U32("graphics/hns_intro/panel1_tiles.bin.lz");
static const u32 sCinMap_Panel1[] = INCBIN_U32("graphics/hns_intro/panel1_map.bin.lz");
static const u16 sCinPal_Panel1[] = INCBIN_U16("graphics/hns_intro/panel1_pal.bin");
static const u32 sCinTiles_Panel2[] = INCBIN_U32("graphics/hns_intro/panel2_tiles.bin.lz");
static const u32 sCinMap_Panel2[] = INCBIN_U32("graphics/hns_intro/panel2_map.bin.lz");
static const u16 sCinPal_Panel2[] = INCBIN_U16("graphics/hns_intro/panel2_pal.bin");
static const u32 sCinTiles_Panel3[] = INCBIN_U32("graphics/hns_intro/panel3_tiles.bin.lz");
static const u32 sCinMap_Panel3[] = INCBIN_U32("graphics/hns_intro/panel3_map.bin.lz");
static const u16 sCinPal_Panel3[] = INCBIN_U16("graphics/hns_intro/panel3_pal.bin");
static const u32 sCinTiles_Panel4[] = INCBIN_U32("graphics/hns_intro/panel4_tiles.bin.lz");
static const u32 sCinMap_Panel4[] = INCBIN_U32("graphics/hns_intro/panel4_map.bin.lz");
static const u16 sCinPal_Panel4[] = INCBIN_U16("graphics/hns_intro/panel4_pal.bin");
static const u32 sCinTiles_Panel5[] = INCBIN_U32("graphics/hns_intro/panel5_tiles.bin.lz");
static const u32 sCinMap_Panel5[] = INCBIN_U32("graphics/hns_intro/panel5_map.bin.lz");
static const u16 sCinPal_Panel5[] = INCBIN_U16("graphics/hns_intro/panel5_pal.bin");
static const u32 sCinTiles_F01[] = INCBIN_U32("graphics/hns_intro/f01_tiles.bin.lz");
static const u32 sCinMap_F01[] = INCBIN_U32("graphics/hns_intro/f01_map.bin.lz");
static const u16 sCinPal_F01[] = INCBIN_U16("graphics/hns_intro/f01_pal.bin");
static const u32 sCinTiles_F02a[] = INCBIN_U32("graphics/hns_intro/f02a_tiles.bin.lz");
static const u32 sCinMap_F02a[] = INCBIN_U32("graphics/hns_intro/f02a_map.bin.lz");
static const u16 sCinPal_F02a[] = INCBIN_U16("graphics/hns_intro/f02a_pal.bin");
static const u32 sCinTiles_F02b[] = INCBIN_U32("graphics/hns_intro/f02b_tiles.bin.lz");
static const u32 sCinMap_F02b[] = INCBIN_U32("graphics/hns_intro/f02b_map.bin.lz");
static const u16 sCinPal_F02b[] = INCBIN_U16("graphics/hns_intro/f02b_pal.bin");
static const u32 sCinTiles_F03[] = INCBIN_U32("graphics/hns_intro/f03_tiles.bin.lz");
static const u32 sCinMap_F03[] = INCBIN_U32("graphics/hns_intro/f03_map.bin.lz");
static const u16 sCinPal_F03[] = INCBIN_U16("graphics/hns_intro/f03_pal.bin");
static const u32 sCinTiles_F04[] = INCBIN_U32("graphics/hns_intro/f04_tiles.bin.lz");
static const u32 sCinMap_F04[] = INCBIN_U32("graphics/hns_intro/f04_map.bin.lz");
static const u16 sCinPal_F04[] = INCBIN_U16("graphics/hns_intro/f04_pal.bin");
static const u32 sCinTiles_F05a[] = INCBIN_U32("graphics/hns_intro/f05a_tiles.bin.lz");
static const u32 sCinMap_F05a[] = INCBIN_U32("graphics/hns_intro/f05a_map.bin.lz");
static const u16 sCinPal_F05a[] = INCBIN_U16("graphics/hns_intro/f05a_pal.bin");
static const u32 sCinTiles_F05b[] = INCBIN_U32("graphics/hns_intro/f05b_tiles.bin.lz");
static const u32 sCinMap_F05b[] = INCBIN_U32("graphics/hns_intro/f05b_map.bin.lz");
static const u16 sCinPal_F05b[] = INCBIN_U16("graphics/hns_intro/f05b_pal.bin");
static const u32 sCinTiles_F06[] = INCBIN_U32("graphics/hns_intro/f06_tiles.bin.lz");
static const u32 sCinMap_F06[] = INCBIN_U32("graphics/hns_intro/f06_map.bin.lz");
static const u16 sCinPal_F06[] = INCBIN_U16("graphics/hns_intro/f06_pal.bin");
static const u32 sCinTiles_F07a[] = INCBIN_U32("graphics/hns_intro/f07a_tiles.bin.lz");
static const u32 sCinMap_F07a[] = INCBIN_U32("graphics/hns_intro/f07a_map.bin.lz");
static const u16 sCinPal_F07a[] = INCBIN_U16("graphics/hns_intro/f07a_pal.bin");
static const u32 sCinTiles_F07b[] = INCBIN_U32("graphics/hns_intro/f07b_tiles.bin.lz");
static const u32 sCinMap_F07b[] = INCBIN_U32("graphics/hns_intro/f07b_map.bin.lz");
static const u16 sCinPal_F07b[] = INCBIN_U16("graphics/hns_intro/f07b_pal.bin");
static const u32 sCinTiles_F08[] = INCBIN_U32("graphics/hns_intro/f08_tiles.bin.lz");
static const u32 sCinMap_F08[] = INCBIN_U32("graphics/hns_intro/f08_map.bin.lz");
static const u16 sCinPal_F08[] = INCBIN_U16("graphics/hns_intro/f08_pal.bin");
static const u32 sCinTiles_F0900[] = INCBIN_U32("graphics/hns_intro/f09_00_tiles.bin.lz");
static const u32 sCinMap_F0900[] = INCBIN_U32("graphics/hns_intro/f09_00_map.bin.lz");
static const u16 sCinPal_F0900[] = INCBIN_U16("graphics/hns_intro/f09_00_pal.bin");
static const u32 sCinTiles_F0901[] = INCBIN_U32("graphics/hns_intro/f09_01_tiles.bin.lz");
static const u32 sCinMap_F0901[] = INCBIN_U32("graphics/hns_intro/f09_01_map.bin.lz");
static const u16 sCinPal_F0901[] = INCBIN_U16("graphics/hns_intro/f09_01_pal.bin");
static const u32 sCinTiles_F0910[] = INCBIN_U32("graphics/hns_intro/f09_10_tiles.bin.lz");
static const u32 sCinMap_F0910[] = INCBIN_U32("graphics/hns_intro/f09_10_map.bin.lz");
static const u16 sCinPal_F0910[] = INCBIN_U16("graphics/hns_intro/f09_10_pal.bin");
static const u32 sCinTiles_F0911[] = INCBIN_U32("graphics/hns_intro/f09_11_tiles.bin.lz");
static const u32 sCinMap_F0911[] = INCBIN_U32("graphics/hns_intro/f09_11_map.bin.lz");
static const u16 sCinPal_F0911[] = INCBIN_U16("graphics/hns_intro/f09_11_pal.bin");
static const u32 sCinTiles_F10[] = INCBIN_U32("graphics/hns_intro/f10_tiles.bin.lz");
static const u32 sCinMap_F10[] = INCBIN_U32("graphics/hns_intro/f10_map.bin.lz");
static const u16 sCinPal_F10[] = INCBIN_U16("graphics/hns_intro/f10_pal.bin");
static const u32 sCinTiles_F11[] = INCBIN_U32("graphics/hns_intro/f11_tiles.bin.lz");
static const u32 sCinMap_F11[] = INCBIN_U32("graphics/hns_intro/f11_map.bin.lz");
static const u16 sCinPal_F11[] = INCBIN_U16("graphics/hns_intro/f11_pal.bin");
static const u32 sCinTiles_F120[] = INCBIN_U32("graphics/hns_intro/f12_0_tiles.bin.lz");
static const u32 sCinMap_F120[] = INCBIN_U32("graphics/hns_intro/f12_0_map.bin.lz");
static const u16 sCinPal_F120[] = INCBIN_U16("graphics/hns_intro/f12_0_pal.bin");
static const u32 sCinTiles_F121[] = INCBIN_U32("graphics/hns_intro/f12_1_tiles.bin.lz");
static const u32 sCinMap_F121[] = INCBIN_U32("graphics/hns_intro/f12_1_map.bin.lz");
static const u16 sCinPal_F121[] = INCBIN_U16("graphics/hns_intro/f12_1_pal.bin");

enum HnsCinPanel {
    CIN_PANEL1,
    CIN_PANEL2,
    CIN_PANEL3,
    CIN_PANEL4,
    CIN_PANEL5,
    CIN_F01,
    CIN_F02A,
    CIN_F02B,
    CIN_F03,
    CIN_F04,
    CIN_F05A,
    CIN_F05B,
    CIN_F06,
    CIN_F07A,
    CIN_F07B,
    CIN_F08,
    CIN_F09_00,
    CIN_F09_01,
    CIN_F09_10,
    CIN_F09_11,
    CIN_F10,
    CIN_F11,
    CIN_F12_0,
    CIN_F12_1,
    CIN_PANEL_COUNT
};

static const struct HnsCinPanelData sCinPanels[CIN_PANEL_COUNT] = {
    [CIN_PANEL1] = {sCinTiles_Panel1, sCinMap_Panel1, sCinPal_Panel1, sizeof(sCinPal_Panel1)},
    [CIN_PANEL2] = {sCinTiles_Panel2, sCinMap_Panel2, sCinPal_Panel2, sizeof(sCinPal_Panel2)},
    [CIN_PANEL3] = {sCinTiles_Panel3, sCinMap_Panel3, sCinPal_Panel3, sizeof(sCinPal_Panel3)},
    [CIN_PANEL4] = {sCinTiles_Panel4, sCinMap_Panel4, sCinPal_Panel4, sizeof(sCinPal_Panel4)},
    [CIN_PANEL5] = {sCinTiles_Panel5, sCinMap_Panel5, sCinPal_Panel5, sizeof(sCinPal_Panel5)},
    [CIN_F01] = {sCinTiles_F01, sCinMap_F01, sCinPal_F01, sizeof(sCinPal_F01)},
    [CIN_F02A] = {sCinTiles_F02a, sCinMap_F02a, sCinPal_F02a, sizeof(sCinPal_F02a)},
    [CIN_F02B] = {sCinTiles_F02b, sCinMap_F02b, sCinPal_F02b, sizeof(sCinPal_F02b)},
    [CIN_F03] = {sCinTiles_F03, sCinMap_F03, sCinPal_F03, sizeof(sCinPal_F03)},
    [CIN_F04] = {sCinTiles_F04, sCinMap_F04, sCinPal_F04, sizeof(sCinPal_F04)},
    [CIN_F05A] = {sCinTiles_F05a, sCinMap_F05a, sCinPal_F05a, sizeof(sCinPal_F05a)},
    [CIN_F05B] = {sCinTiles_F05b, sCinMap_F05b, sCinPal_F05b, sizeof(sCinPal_F05b)},
    [CIN_F06] = {sCinTiles_F06, sCinMap_F06, sCinPal_F06, sizeof(sCinPal_F06)},
    [CIN_F07A] = {sCinTiles_F07a, sCinMap_F07a, sCinPal_F07a, sizeof(sCinPal_F07a)},
    [CIN_F07B] = {sCinTiles_F07b, sCinMap_F07b, sCinPal_F07b, sizeof(sCinPal_F07b)},
    [CIN_F08] = {sCinTiles_F08, sCinMap_F08, sCinPal_F08, sizeof(sCinPal_F08)},
    [CIN_F09_00] = {sCinTiles_F0900, sCinMap_F0900, sCinPal_F0900, sizeof(sCinPal_F0900)},
    [CIN_F09_01] = {sCinTiles_F0901, sCinMap_F0901, sCinPal_F0901, sizeof(sCinPal_F0901)},
    [CIN_F09_10] = {sCinTiles_F0910, sCinMap_F0910, sCinPal_F0910, sizeof(sCinPal_F0910)},
    [CIN_F09_11] = {sCinTiles_F0911, sCinMap_F0911, sCinPal_F0911, sizeof(sCinPal_F0911)},
    [CIN_F10] = {sCinTiles_F10, sCinMap_F10, sCinPal_F10, sizeof(sCinPal_F10)},
    [CIN_F11] = {sCinTiles_F11, sCinMap_F11, sCinPal_F11, sizeof(sCinPal_F11)},
    [CIN_F12_0] = {sCinTiles_F120, sCinMap_F120, sCinPal_F120, sizeof(sCinPal_F120)},
    [CIN_F12_1] = {sCinTiles_F121, sCinMap_F121, sCinPal_F121, sizeof(sCinPal_F121)},
};
